# Site settings 配置站点
title: 'Blog de Saerohsi'
description: 'Just for fun !'
keywords: 'Saeroshi, blog de Saeroshi, blog Saerosi, linux, sysadmin'
url: 'https://www.saeroshi.xyz' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  Accueil: '/'
  Tags: '/tags.html'
  Timeline: '/timeline.html'
  À propos: '/about.html'
#  个人简历: '/resume/index.html'
  Friends: '/friendLink.html'

# 博主
author: true
name: 'Saeroshi Godai'
NickName: 'Saeroshi'
webtitle: 'Saeroshi'
bio: 'Crypto-anarchiste à tendance paranoïaque, cultivateur de systèmes et apprenti éleveur de manchot.'
about: true
aboutyou: 'A Faire :D
        '
portraits: '/assets/profile.png'

# SNS
SNS: false
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:'
  github: ''
  Codepen: ''
  weixin: '/assets/scan/wechat.JPG'
  # qq: '/assets/scan/qq.JPG'
  qq: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  # Dribbble: ''
  # Facebook: ''
  # Google: ''
  # zhihu: ''
  # juejin: ''
  # twitch: ''

# 分页
paginate: 5
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
ighlighter: rouge
pygmentsTheme: 'tango'

friends:
  The Daily Florian: 'https://daily.floerens.eu/'

disqus: false
disqus_url: 'https://talkcock.disqus.com/embed.js'

livere: false
livere_uid: ''
Gitment: false
Gitment_owner: ''
Gitment_repo: ''
client_id: ''
client_secret: ''

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: false
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

baidu: false
baidu-url: ''
google: false
google-ID: ''

color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
